### ISSUE TITLE
Mutlitple errors in GUI file 

### ISSUE THREAD

**Issue by ali50mahmoud** [kartikmadhira1/Traffic-Counter_OpenCV#1]
GUI file won't compile due to numerous errors in the `addActionListener()` method 

`  playPauseButton.addActionListener(event -> {...`

error : `cannot find symbol symbol : variable event`

**Comment by kartikmadhira1** [comment]
Please check your version of OpenCV, must be other than 3.0 as far as I remember. Also, GUI issues are to resolved with correct version. Not a code issue.

**Comment by ali50mahmoud** [comment]
open cv in libraries folder is used
